[package]
name = "buttplug-rs-ffi"
version = "1.0.12"
description = "FFI Layer for buttplug-rs. Used by other languages for implementing buttplug-rs bindings."
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["buttplug/async-std-runtime", "buttplug/btleplug-manager", "buttplug/websockets", "buttplug/xinput-manager", "buttplug/serial-manager", "buttplug/lovense-dongle-manager", "log-panics"]
wasm = ["wasm-bindgen", "uuid", "web-sys", "js-sys", "tracing-wasm", "buttplug/wasm-bindgen-runtime", "async-trait", "wasm-bindgen-futures", "console_error_panic_hook"]

[dependencies]
buttplug = { version = "2.1.3", default-features = false, features = ["client", "server", "serialize-json"] }
# buttplug = { path = "../../buttplug-rs/buttplug", default-features = false, features = ["client", "server", "serialize-json"] }
async-std = "1.9.0"
tracing-subscriber = "0.2.15"
futures = "0.3.12"
tracing = "0.1.23"
dashmap = "4.0.2"
libc = "0.2.86"
prost = "0.7.0"
async-channel = "1.5.1"
lazy_static = "1.4.0"
wasm-bindgen = { version = "0.2.70", features = ["serde-serialize"], optional = true }
# Needed to build valico with wasm-bindgen
uuid = { version = "0.8.2", features = ["wasm-bindgen"], optional = true }
async-lock = "2.3.0"
js-sys = { version = "0.3.47", optional = true }
tracing-wasm = { version = "0.1.0", optional = true }
async-trait = { version = "0.1.42", optional = true }
wasm-bindgen-futures = { version = "0.4.20", optional = true }
tokio = { version = "1.2.0", features = ["sync"] }
log-panics = { version = "2.0.0", optional = true, features = ["with-backtrace"] }
console_error_panic_hook = { version = "0.1.6", optional = true }

[build-dependencies]
prost-build = "0.7.0"
vergen = "3.2.0"

[lib]
name = "buttplug_rs_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3.47"
# path = "../../wasm-bindgen/crates/web-sys"
#git = "https://github.com/rustwasm/wasm-bindgen"
optional = true
features = [
  "Navigator",
  "Bluetooth",
  "BluetoothDevice",
  "BluetoothLeScanFilterInit",
  "BluetoothRemoteGattCharacteristic",
  "BluetoothRemoteGattServer",
  "BluetoothRemoteGattService",
  "BinaryType",
  "Blob",
  "console",
  # "DataView",
  "ErrorEvent",
  "Event",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "RequestDeviceOptions",
  "WebSocket",
  "Window"
]
